### ISSUE TITLE
Fix BaseView Snackbar implementation

### ISSUE THREAD

**Issue by jshvarts** [exallium/todoapp#21]
1) Ensure that `displaySnackbar(@StringRes stringResourceId: Int, @BaseTransientBottomBar.Duration length: Int = Snackbar.LENGTH_SHORT)` works. We should be attaching it to the root view.

2) Remove `fun displaySnackbar(string: String, @BaseTransientBottomBar.Duration length: Int = Snackbar.LENGTH_SHORT)` as we should be going thru Resources to future-proof for internationalization.

**Comment by jshvarts** [comment]
Hey @exallium 

After debugging this I noticed that in `BaseViewImpl` `val view = inflater.inflate(getLayoutId(), container, false)` successfully inflates a view on All Notes screen but produces a null `view` on Note Detail screen. That's why Snackbar does not come up on Note Detail screen. I have not been able to figure this out--do you have any ideas?

**Comment by exallium** [comment]
Hmm.  My only thought is that getLayoutId() is not set correctly, or that the container is null somehow.

**Comment by jshvarts** [comment]
Layout ID is set correctly and the view group is the same as the all notes
view

**Comment by exallium** [comment]
Things I would check:

1) Are you trying to call displaySnackbar before Butterknife binds
2) Is the container being passed into inflate null
3) If you clean and rebuild, do you get a different result

**Comment by jshvarts** [comment]
checked all 3--no luck

**Comment by jshvarts** [comment]
the issue was simply `.show()` was not called :)
